[package]
name = "el_monitorro"
version = "0.1.0"
authors = ["Ayrat Badykov <ayratin555@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
rake = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rss = { version = "1.0", features = ["from_url"] }
mockall = "0.6.0"
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "chrono"] }

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json"]

[dev-dependencies]
once_cell = "1.3.0"