[package]
name = "el_monitorro"
version = "0.1.0"
authors = ["Ayrat Badykov <ayratin555@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clokwerk = "0.3"
diesel = { version = "1.4", features = ["postgres", "chrono"] }
dotenv = "0.15.0"
env_logger = "0.7.1"
failure = "0.1"
izta = "0.1.2"
log = "0.4.0"
mockall = "0.6.0"
once_cell = "1.3.0"
rake = "0.1"
rocket = "0.4.2"
rss = { version = "1.0", features = ["from_url"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "diesel_postgres_pool"]
