name: docs

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        submodules: 'recursive'
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - run: |
        cp ./README.md ./docs/content/_index.md
    - run: |
        cp ./CHANGELOG.md ./docs/content/changelog.md
    - name: Deloy docs
      run: |
        source ./docs/deploy.sh && build && deploy
